# Generated by Django 4.2.6 on 2024-02-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentedUavs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uav', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('member', models.CharField(max_length=200)),
            ],
        ),
    ]
