# Generated by Django 4.2.6 on 2024-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
